baseURL = "https://biopuces.netlify.app"
languageCode = "en-us"
title = "Biopuces"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Biopuces"
    description = "Groupe de travail"
    githubUsername = "Biopuces"
    accent = "#50C878	"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "Propulsé par [Blogdown](https://github.com/rstudio/blogdown), [Hugo](https://gohugo.io), [Minimal](https://github.com/calintat/minimal), [GitHub](https://github.com/) et [netlify](https://www.netlify.com/)."


[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "À propos"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Présentation"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://groupes.renater.fr/sympa/info/biopuces"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Biopuces"
    name = "fab fa-github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "fab fa-twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "fab fa-linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5
