---
title: Multiblock data analysis with the RGCCA package, Arthur Tenenhaus
author: ''
date: '2025-12-09'
slug: []
categories: []
tags: []
---

Séance exceptionnelle en collaboration avec le réseau [StateOftheR](https://stateofther.netlify.app/), présentation d'Arthur Tenenhaus autour de l'analyse de données multi-blocs avec le package R *RGCCA*.

Multiblock data analysis with the RGCCA package
 
**Abstract**

Multiblock component methods are essential tools for exploring complex relationships between
multiple sets of variables. Although various statistical methods and dedicated software for
multiblock data analysis exist, Regularized Generalized Canonical Correlation Analysis (RGCCA)
offers a unified and versatile framework that consolidates more than six decades of multiblock
component methods. During this half-day practical session, we will present the RGCCA framework 
and the RGCCA package, which implements this framework and goes beyond by providing graphical 
outputs and statistical tools to assess the robustness and significance of the analysis. The usefulness 
of the RGCCA package will be illustrated through two real-world case studies. The package is freely 
available from the Comprehensive R Archive Network (CRAN) at https://CRAN.R-project.org/package=RGCCA and
from GitHub at https://github.com/rgcca-factory/RGCCA.
 
**Slides**

Les diapositives de la séance sont disponibles ici : [pdf](/diapos/RGCCA@Agro.pdf) and the [Rmd file](/diapos/tutorial_rgcca_package.Rmd)

**Quelques références**

* Girka, F., Camenen, E., Peltier, C., Gloaguen, A., Guillemot, V., Le Brusquet, L., & Tenenhaus, A. (2025). Multiblock data analysis with the RGCCA package. Journal of Statistical Software, 1-36.
https://cran.r-project.org/web/packages/RGCCA/vignettes/RGCCA.pdf

* Sort L., Le Brusquet L., Tenenhaus A. (2024) Functional Generalized Canonical Correlation Analysis for studying multiple longitudinal variables, Biometrics, 80(4) ([doi](https://doi.org/10.1093/biomtc/ujae113))

* Girka, F., Gloaguen, A., Le Brusquet, L., Zujovic, V., & Tenenhaus, A. (2024). Tensor generalized canonical correlation analysis. Information Fusion, 102, 102045. ([doi](https://doi.org/10.1016/j.inffus.2023.102045))

* Gloaguen A., Philippe C., Frouin V., Gennari G., Dehaene-Lambertz G., Le Brusquet L., Tenenhaus A., (2022) Multiway Generalized Canonical Correlation Analysis, Biostatistics, 23(1), 240-256. ([doi](https://doi.org/10.1093/biostatistics/kxaa010))

* Tenenhaus M, Tenenhaus A, Groenen PJF, (2017) Regularized generalized canonical correlation analysis: A framework for sequential multiblock component methods, Psychometrika, vol. 82, no. 3, 737–777 ([doi](https://doi.org/10.1007/s11336-017-9573-x))

* Tenenhaus A, Philippe C, Frouin V (2015) Kernel generalized canonical correlation analysis, Computational Statistics & Data Analysis, vol. 90, pp. 114-131. ([doi](https://doi.org/10.1016/j.csda.2015.04.004))

* Tenenhaus, A., Tenenhaus, M. (2014). Regularized generalized canonical correlation analysis for multiblock or multigroup data analysis. European Journal of operational research, 238(2), 391-403. ([doi](https://doi.org/10.1016/j.ejor.2014.01.008))

* Tenenhaus A., Philippe C., Guillemot V, et al..(2014). Variable Selection for Generalized Canonical Correlation Analysis, Biostatistics, 15 (3) : 569-583 ([doi](https://doi.org/10.1093/biostatistics/kxu001))

* Tenenhaus A, Tenenhaus M (2011) Regularized generalized canonical correlation analysis, vol. 76, pp. 257-284, Psychometrika ([doi](https://doi.org/10.1007/s11336-011-9206-8))

**Autre**

N'hésitez pas à aller voir les présentations du réseau StateOftheR : https://stateofther.netlify.app/
