---
title: Intégration de données omiques et sélection de variables, Céline Bougel
author: ''
date: '2024-11-06'
slug: []
categories: []
tags: 

- intégration de données
- sélection de variables
---

Présentation de **Céline Bougel**

Intégration de données omiques et sélection de variables.

<!-- Vous trouverez la présentation via ce lien : [pdf](/diapos/nom_pres.pdf). -->

### Résumé  

Dans le cadre du projet ANR MTH2.0 WP1.4, j'avais deux missions. Pour la première mission, j'ai développé un package R innovant pour intégrer des données -omiques, en traduisant et enrichissant une méthode initialement conçue sous Matlab. Cette première version du package inclut déjà des améliorations significatives, avec encore d'autres fonctionnalités en cours de développement.
Pour la seconde mission, nous faisons face à un défi majeur inhérent aux données -omiques : leur grande dimensionnalité, souvent associée à une redondance d'information. Pour relever ce défi et extraire uniquement les éléments les plus pertinents pour nos modèles statistiques, nous explorons des méthodes avancées de sélection de variables. Celles-ci permettent de réduire la complexité des données tout en maintenant leur richesse informative.
Lors de cette présentation, je vous exposerai les méthodes que j'ai sélectionnées, et vous montrerai leur application sur des données réelles.
